site:
  title: The Starknet Book
  start_page: ROOT::index.adoc
  keys:
    google_analytics: 'G-WY42TERK5P'

content:
  sources:
  - url: .
    branches: HEAD
    edit_url: 'https://github.com/starknet-edu/starknetbook/edit/main/{path}'
    start_paths:
      - chapters/book

ui:
  bundle:
    url: https://github.com/starknet-io/starknet-docs-antora-ui/raw/HEAD/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./ui/supplemental_ui

runtime:
  fetch: true

asciidoc:
  attributes:
    idprefix: ''
    stem: 'latexmath'
    page-pagination: ''
    experimental: ''

antora:
  extensions:
  - '@antora/lunr-extension'

output:
  destinations:
  - provider: fs
    path: ./public_html/
    clean: true
